# Generated by Django 3.0.8 on 2020-07-14 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200714_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 12, 22, 11, 28439, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
